//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDtls
    {
        public int id { get; set; }
        public string txtType { get; set; }
        public Nullable<double> amount { get; set; }
        public string remarks { get; set; }
        public int mentorId { get; set; }
        public string mentorName { get; set; }
        public int trainingId { get; set; }
        public string skillName { get; set; }
        public Nullable<double> totalAmountToMentor { get; set; }
    }
}
