//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDtl
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> trainerId { get; set; }
        public Nullable<int> skillId { get; set; }
        public Nullable<double> fees { get; set; }
        public Nullable<double> trainerFees { get; set; }
        public Nullable<double> commision { get; set; }
        public string skillName { get; set; }
        public Nullable<bool> paymentStatus { get; set; }
        public Nullable<int> trainingDetailsId { get; set; }
    }
}
